# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('polls', '0001_initial'), ('polls', '0002_auto_20160419_1416'), ('polls', '0002_auto_20160419_1013'), ('polls', '0003_merge'), ('polls', '0004_login'), ('polls', '0005_xat'), ('polls', '0006_auto_20160426_2037'), ('polls', '0007_calendar'), ('polls', '0008_auto_20160429_1242'), ('polls', '0009_notacalendario'), ('polls', '0010_auto_20160429_1305'), ('polls', '0011_auto_20160429_1310'), ('polls', '0012_auto_20160429_1320'), ('polls', '0013_notacalendario'), ('polls', '0014_auto_20160510_2007'), ('polls', '0015_auto_20160510_2010'), ('polls', '0016_persona_btc_address'), ('polls', '0017_notacalendario')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localitat', models.CharField(max_length=200)),
                ('adressa', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Xat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=b'')),
                ('preu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognoms', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('id_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cases')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('btc_address', models.CharField(max_length=34, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Persona'),
        ),
        migrations.CreateModel(
            name='NotaCalendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateField', models.DateField(auto_now_add=True)),
                ('nota', models.CharField(max_length=2000)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Persona')),
            ],
        ),
    ]
